# name: Selenium Tests on BrowserStack

# on: [push]

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Go
#         uses: actions/setup-go@v4
#         with:
#           go-version: '1.26'

#       - name: Build and Start Go Backend
#         run: |
#           cd ./Zadanie-5/backend
#           go mod download
#           go build -o server main.go
          
#           ./server > backend.log 2>&1 &
          
#           sleep 20
          
#           echo "--- LOGI BACKENDU ---"
#           cat backend.log

#       - name: Verify Backend Port
#         run: |
#           curl -I http://localhost:8080/products

#       - name: Verify Data
#         run: |
#           curl -s http://localhost:8080/products

#       - name: Set up Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.9'

#       - name: Install Python dependencies
#         run: pip install pytest selenium requests

#       - name: Install Frontend dependencies
#         working-directory: ./Zadanie-5/frontend
#         run: npm install

#       - name: Start Frontend (React)
#         working-directory: ./Zadanie-5/frontend
#         run: npm run dev -- --host 0.0.0.0 &

#       - name: Set up BrowserStack Env
#         uses: browserstack/github-actions/setup-env@master
#         with:
#           username: ${{ secrets.BROWSERSTACK_USERNAME }}
#           access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

#       - name: BrowserStack Local
#         uses: browserstack/github-actions/setup-local@master
#         with:
#           local-testing: start
#           local-identifier: 'zadanie-6'
#         env:
#           BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

#       - name: Run Tests
#         env:
#           BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
#           BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
#         run: |
#           sleep 20
#           pytest Zadanie-6/functional_test.py